// Maps NSE/BSE stock symbols to their official company web domains.
// These domains are used with Clearbit's Logo API (https://logo.clearbit.com/<domain>)
// to render real company logos.
export const STOCK_DOMAINS: Record<string, string> = {
  RELIANCE: 'ril.com',
  TCS: 'tcs.com',
  HDFCBANK: 'hdfcbank.com',
  INFY: 'infosys.com',
  ICICIBANK: 'icicibank.com',
  HINDUNILVR: 'hul.co.in',
  SBIN: 'sbi.co.in',
  BHARTIARTL: 'airtel.in',
  ITC: 'itcportal.com',
  BAJFINANCE: 'bajajfinserv.in',
  LT: 'larsentoubro.com',
  KOTAKBANK: 'kotak.com',
  AXISBANK: 'axisbank.com',
  MARUTI: 'marutisuzuki.com',
  ASIANPAINT: 'asianpaints.com',
  WIPRO: 'wipro.com',
  HCLTECH: 'hcltech.com',
  TATAMOTORS: 'tatamotors.com',
  TATASTEEL: 'tatasteel.com',
  ADANIENT: 'adanienterprises.com',
  ADANIPORTS: 'adaniports.com',
  ONGC: 'ongcindia.com',
  NTPC: 'ntpc.co.in',
  POWERGRID: 'powergrid.in',
  COALINDIA: 'coalindia.in',
  SUNPHARMA: 'sunpharma.com',
  DRREDDY: 'drreddys.com',
  CIPLA: 'cipla.com',
  NESTLEIND: 'nestle.in',
  TITAN: 'titancompany.in',
  BAJAJFINSV: 'bajajfinserv.in',
  ULTRACEMCO: 'ultratechcement.com',
  JSWSTEEL: 'jsw.in',
  TECHM: 'techmahindra.com',
  BRITANNIA: 'britannia.co.in',
  DIVISLAB: 'divislaboratories.com',
  EICHERMOT: 'eicher.in',
  GRASIM: 'grasim.com',
  HEROMOTOCO: 'heromotocorp.com',
  INDUSINDBK: 'indusind.com',
  SBILIFE: 'sbilife.co.in',
  HDFCLIFE: 'hdfclife.com',
  TATACONSUM: 'tataconsumer.com',
  UPL: 'upl-ltd.com',
  BPCL: 'bharatpetroleum.in',
  IOC: 'iocl.com',
  HINDALCO: 'hindalco.com',
  ZOMATO: 'zomato.com',
  PAYTM: 'paytm.com',
  NYKAA: 'nykaa.com',
  // Additional major stocks
  ACC: 'acc.com',
  AMBUJACEM: 'ambujacement.com',
  DLF: 'dlf.in',
  GODREJPROP: 'godrejproperties.com',
  TATACHEM: 'tatachemicals.com',
  TATACOMM: 'tatacommunications.com',
  TATAPOWER: 'tatapower.com',
  VEDL: 'vedanta.com',
  NMDC: 'nmdc.co.in',
  GAIL: 'gailonline.com',
  BANKBARODA: 'bankofbaroda.com',
  PNB: 'pnbindia.in',
  CANBK: 'canarabank.com',
  UNIONBANK: 'unionbankofindia.com',
  IDFCFIRSTB: 'idfcfirstbank.com',
  BANDHANBNK: 'bandhanbank.com',
  FEDERALBNK: 'federalbank.co.in',
  AUROPHARMA: 'aurobindopharma.com',
  LUPIN: 'lupin.com',
  ABBOTINDIA: 'abbott.com',
  PFIZER: 'pfizer.com',
  GLENMARK: 'glenmarkpharma.com',
  MCDOWELLN: 'usl.in',
  IGL: 'indianagas.com',
  MUTHOOTFIN: 'muthootfinance.com',
  MANAPPURAM: 'manappuram.com',
  BAJAJAUTO: 'bajajauto.com',
  ESCORTS: 'escorts.co.in',
  EXIDEIND: 'exideindustries.com',
  AMARAJABAT: 'amaronbatteries.com',
  APOLLOHOSP: 'apollohospitals.com',
  MAXHEALTH: 'maxhealthcare.com',
  FORTIS: 'fortishealthcare.com',
  LALPATHLAB: 'lalpathlabs.com',
  APOLLOTYRE: 'apollotyres.com',
  MRF: 'mrftyres.com',
  CEAT: 'ceat.com',
  JKTYRE: 'jktyre.com',
  BALKRISIND: 'balkrishna.com',
  SIEMENS: 'siemens.com',
  ABB: 'abb.com',
  BOSCHLTD: 'bosch.com',
  SCHAEFFLER: 'schaeffler.com',
  TIMKEN: 'timken.com',
  SKFINDIA: 'skf.com',
  BEML: 'bemlindia.com',
  BEL: 'bel-india.com',
  HAL: 'hal-india.com',
  MTNL: 'mtnl.in',
  IDEA: 'vodafoneidea.com',
  TATAMTRDVR: 'tatamotors.com',
  RPOWER: 'reliancepower.com',
  RNAM: 'reliancenippon.com',
  TVSMOTOR: 'tvsmotor.com',
  ASHOKLEY: 'ashokleyland.com',
  FORCEMOT: 'forcemotors.com',
  PERSISTENT: 'persistent.co.in',
  LTIMINDTREE: 'ltimindtree.com',
  MINDTREE: 'mindtree.com',
  MPHASIS: 'mphasis.com',
  RELINFRA: 'relianceinfra.com',
  GMRINFRA: 'gmrgroup.in',
  ADANIGREEN: 'adanigreenenergy.com',
  ADANIGAS: 'adanigas.com',
  ADANITRANS: 'adaniports.com',
  ADANIPOWER: 'adani.com',
  HINDUSTAN: 'hindustanunilever.com',
  GODREJCP: 'godrejcp.com',
  GODREJIND: 'godrej.com',
  TANLA: 'tanla.com',
  NATCOPHARM: 'natcopharma.com',
  ZYDUSLIFE: 'zyduslife.com',
  TORNTPHARM: 'torrentpharma.com',
  JUBLPHARMA: 'jublpharma.com',
  ASTRAL: 'astralpoly.com',
  POLYPLEX: 'polyplex.com',
  SRF: 'srf.com',
  PIIND: 'piind.com',
  DEEPAKNTR: 'deepaknitrite.com',
  NAVINFLUOR: 'navinfluorine.com',
  GUJALKALI: 'gujalkali.com',
  CHAMBLFERT: 'chambalfertilizers.com',
  COROMANDEL: 'coromandel.com',
  RALLIS: 'rallis.com',
  Dhanuka: 'dhanuka.com',
  BASF: 'basf.com',
  BAYERCROP: 'bayer.com',
  SUMICHEM: 'sumichem.com',
  DEEPAKFERT: 'deepakfertilisers.com',
  GNFC: 'gnfc.in',
  GSFC: 'gsfc.in',
  GUJGASLTD: 'gujratgas.com',
  MGL: 'mahanagargas.com',
  OIL: 'oil-india.com',
  CAIRN: 'cairnindia.com',
  PETRONET: 'petronetlng.com',
};

// US equity logos. Same DuckDuckGo favicon trick — every domain returns the
// corresponding company's favicon, which is the cleanest free logo source.
export const US_STOCK_DOMAINS: Record<string, string> = {
  // Mag 7 + megacap tech
  AAPL: 'apple.com',
  MSFT: 'microsoft.com',
  GOOGL: 'abc.xyz',
  GOOG: 'abc.xyz',
  AMZN: 'amazon.com',
  META: 'meta.com',
  NVDA: 'nvidia.com',
  TSLA: 'tesla.com',
  // Semis
  AMD: 'amd.com',
  INTC: 'intel.com',
  AVGO: 'broadcom.com',
  QCOM: 'qualcomm.com',
  TXN: 'ti.com',
  MU: 'micron.com',
  AMAT: 'appliedmaterials.com',
  KLAC: 'kla.com',
  LRCX: 'lamresearch.com',
  // Software / Internet
  ORCL: 'oracle.com',
  CRM: 'salesforce.com',
  ADBE: 'adobe.com',
  NFLX: 'netflix.com',
  IBM: 'ibm.com',
  CSCO: 'cisco.com',
  SHOP: 'shopify.com',
  PLTR: 'palantir.com',
  SMCI: 'supermicro.com',
  // Financials
  JPM: 'jpmorganchase.com',
  BAC: 'bankofamerica.com',
  WFC: 'wellsfargo.com',
  C: 'citigroup.com',
  GS: 'goldmansachs.com',
  MS: 'morganstanley.com',
  V: 'visa.com',
  MA: 'mastercard.com',
  PYPL: 'paypal.com',
  SQ: 'block.xyz',
  COIN: 'coinbase.com',
  'BRK-B': 'berkshirehathaway.com',
  // Healthcare
  JNJ: 'jnj.com',
  PFE: 'pfizer.com',
  UNH: 'unitedhealthgroup.com',
  LLY: 'lilly.com',
  ABBV: 'abbvie.com',
  MRK: 'merck.com',
  // Energy
  XOM: 'exxonmobil.com',
  CVX: 'chevron.com',
  COP: 'conocophillips.com',
  // Consumer
  WMT: 'walmart.com',
  COST: 'costco.com',
  KO: 'coca-cola.com',
  PEP: 'pepsico.com',
  PG: 'pg.com',
  HD: 'homedepot.com',
  NKE: 'nike.com',
  MCD: 'mcdonalds.com',
  SBUX: 'starbucks.com',
  DIS: 'thewaltdisneycompany.com',
  // Industrials
  BA: 'boeing.com',
  CAT: 'caterpillar.com',
  GE: 'ge.com',
  UPS: 'ups.com',
  // Telecom
  T: 'att.com',
  VZ: 'verizon.com',
  // Travel
  UBER: 'uber.com',
  ABNB: 'airbnb.com',
  // Autos
  F: 'ford.com',
  GM: 'gm.com',
};

// Consistent fallback background colors (by first letter).
const PALETTE = [
  '#6366F1', '#EC4899', '#F59E0B', '#10B981', '#0EA5E9',
  '#8B5CF6', '#F43F5E', '#14B8A6', '#F97316', '#3B82F6',
];

export function getLogoUrl(symbol: string): string | null {
  const key = symbol.toUpperCase();
  // Check IN first (most common), then US.
  const domain = STOCK_DOMAINS[key] || US_STOCK_DOMAINS[key];
  if (!domain) return null;
  // Use DuckDuckGo favicon service - each domain gets its correct logo
  return `https://icons.duckduckgo.com/ip3/${domain}.ico`;
}

export function getInitialsColor(symbol: string): string {
  const code = symbol.toUpperCase().charCodeAt(0) || 65;
  return PALETTE[code % PALETTE.length];
}
