// Maps NSE/BSE stock symbols to their official company web domains.
// These domains are used with Clearbit's Logo API (https://logo.clearbit.com/<domain>)
// to render real company logos.
export const STOCK_DOMAINS: Record<string, string> = {
  RELIANCE: 'ril.com',
  TCS: 'tcs.com',
  HDFCBANK: 'hdfcbank.com',
  INFY: 'infosys.com',
  ICICIBANK: 'icicibank.com',
  HINDUNILVR: 'hul.co.in',
  SBIN: 'sbi.co.in',
  BHARTIARTL: 'airtel.in',
  ITC: 'itcportal.com',
  BAJFINANCE: 'bajajfinserv.in',
  LT: 'larsentoubro.com',
  KOTAKBANK: 'kotak.com',
  AXISBANK: 'axisbank.com',
  MARUTI: 'marutisuzuki.com',
  ASIANPAINT: 'asianpaints.com',
  WIPRO: 'wipro.com',
  HCLTECH: 'hcltech.com',
  TATAMOTORS: 'tatamotors.com',
  TATASTEEL: 'tatasteel.com',
  ADANIENT: 'adanienterprises.com',
  ADANIPORTS: 'adaniports.com',
  ONGC: 'ongcindia.com',
  NTPC: 'ntpc.co.in',
  POWERGRID: 'powergrid.in',
  COALINDIA: 'coalindia.in',
  SUNPHARMA: 'sunpharma.com',
  DRREDDY: 'drreddys.com',
  CIPLA: 'cipla.com',
  NESTLEIND: 'nestle.in',
  TITAN: 'titancompany.in',
  BAJAJFINSV: 'bajajfinserv.in',
  ULTRACEMCO: 'ultratechcement.com',
  JSWSTEEL: 'jsw.in',
  TECHM: 'techmahindra.com',
  BRITANNIA: 'britannia.co.in',
  DIVISLAB: 'divislaboratories.com',
  EICHERMOT: 'eicher.in',
  GRASIM: 'grasim.com',
  HEROMOTOCO: 'heromotocorp.com',
  INDUSINDBK: 'indusind.com',
  SBILIFE: 'sbilife.co.in',
  HDFCLIFE: 'hdfclife.com',
  TATACONSUM: 'tataconsumer.com',
  UPL: 'upl-ltd.com',
  BPCL: 'bharatpetroleum.in',
  IOC: 'iocl.com',
  HINDALCO: 'hindalco.com',
  ZOMATO: 'zomato.com',
  PAYTM: 'paytm.com',
  NYKAA: 'nykaa.com',
  // Additional major stocks
  ACC: 'acc.com',
  AMBUJACEM: 'ambujacement.com',
  DLF: 'dlf.in',
  GODREJPROP: 'godrejproperties.com',
  TATACHEM: 'tatachemicals.com',
  TATACOMM: 'tatacommunications.com',
  TATAPOWER: 'tatapower.com',
  VEDL: 'vedanta.com',
  NMDC: 'nmdc.co.in',
  GAIL: 'gailonline.com',
  BANKBARODA: 'bankofbaroda.com',
  PNB: 'pnbindia.in',
  CANBK: 'canarabank.com',
  UNIONBANK: 'unionbankofindia.com',
  IDFCFIRSTB: 'idfcfirstbank.com',
  BANDHANBNK: 'bandhanbank.com',
  FEDERALBNK: 'federalbank.co.in',
  AUROPHARMA: 'aurobindopharma.com',
  LUPIN: 'lupin.com',
  ABBOTINDIA: 'abbott.com',
  PFIZER: 'pfizer.com',
  GLENMARK: 'glenmarkpharma.com',
  MCDOWELLN: 'usl.in',
  IGL: 'indianagas.com',
  MUTHOOTFIN: 'muthootfinance.com',
  MANAPPURAM: 'manappuram.com',
  BAJAJAUTO: 'bajajauto.com',
  ESCORTS: 'escorts.co.in',
  EXIDEIND: 'exideindustries.com',
  AMARAJABAT: 'amaronbatteries.com',
  APOLLOHOSP: 'apollohospitals.com',
  MAXHEALTH: 'maxhealthcare.com',
  FORTIS: 'fortishealthcare.com',
  LALPATHLAB: 'lalpathlabs.com',
  APOLLOTYRE: 'apollotyres.com',
  MRF: 'mrftyres.com',
  CEAT: 'ceat.com',
  JKTYRE: 'jktyre.com',
  BALKRISIND: 'balkrishna.com',
  SIEMENS: 'siemens.com',
  ABB: 'abb.com',
  BOSCHLTD: 'bosch.com',
  SCHAEFFLER: 'schaeffler.com',
  TIMKEN: 'timken.com',
  SKFINDIA: 'skf.com',
  BEML: 'bemlindia.com',
  BEL: 'bel-india.com',
  HAL: 'hal-india.com',
  MTNL: 'mtnl.in',
  IDEA: 'vodafoneidea.com',
  TATAMTRDVR: 'tatamotors.com',
  RPOWER: 'reliancepower.com',
  RNAM: 'reliancenippon.com',
  TVSMOTOR: 'tvsmotor.com',
  ASHOKLEY: 'ashokleyland.com',
  FORCEMOT: 'forcemotors.com',
  PERSISTENT: 'persistent.co.in',
  LTIMINDTREE: 'ltimindtree.com',
  MINDTREE: 'mindtree.com',
  MPHASIS: 'mphasis.com',
  RELINFRA: 'relianceinfra.com',
  GMRINFRA: 'gmrgroup.in',
  ADANIGREEN: 'adanigreenenergy.com',
  ADANIGAS: 'adanigas.com',
  ADANITRANS: 'adaniports.com',
  ADANIPOWER: 'adani.com',
  HINDUSTAN: 'hindustanunilever.com',
  GODREJCP: 'godrejcp.com',
  GODREJIND: 'godrej.com',
  TANLA: 'tanla.com',
  NATCOPHARM: 'natcopharma.com',
  ZYDUSLIFE: 'zyduslife.com',
  TORNTPHARM: 'torrentpharma.com',
  JUBLPHARMA: 'jublpharma.com',
  ASTRAL: 'astralpoly.com',
  POLYPLEX: 'polyplex.com',
  SRF: 'srf.com',
  PIIND: 'piind.com',
  DEEPAKNTR: 'deepaknitrite.com',
  NAVINFLUOR: 'navinfluorine.com',
  GUJALKALI: 'gujalkali.com',
  CHAMBLFERT: 'chambalfertilizers.com',
  COROMANDEL: 'coromandel.com',
  RALLIS: 'rallis.com',
  Dhanuka: 'dhanuka.com',
  BASF: 'basf.com',
  BAYERCROP: 'bayer.com',
  SUMICHEM: 'sumichem.com',
  DEEPAKFERT: 'deepakfertilisers.com',
  GNFC: 'gnfc.in',
  GSFC: 'gsfc.in',
  GUJGASLTD: 'gujratgas.com',
  MGL: 'mahanagargas.com',
  OIL: 'oil-india.com',
  CAIRN: 'cairnindia.com',
  PETRONET: 'petronetlng.com',
};

// Consistent fallback background colors (by first letter).
const PALETTE = [
  'D6366F1', 'DEC4899', 'DF59E0B', 'DD4AF37', 'D0EA5E9',
  'D8B5CF6', 'DF43F5E', 'D14B8A6', 'DF97316', 'D3B82F6',
];

export function getLogoUrl(symbol: string): string | null {
  const key = symbol.toUpperCase();
  const domain = STOCK_DOMAINS[key];
  if (!domain) return null;
  // Use DuckDuckGo favicon service - each domain gets its correct logo
  return `https://icons.duckduckgo.com/ip3/${domain}.ico`;
}

export function getInitialsColor(symbol: string): string {
  const code = symbol.toUpperCase().charCodeAt(0) || 65;
  return PALETTE[code % PALETTE.length];
}
